/**
 * MedScript Reference Hub — armazenamento de dados.
 *
 * Este arquivo é REESCRITO pela skill diária `medscript-daily`. A página o
 * carrega via <script> (sem fetch, funciona em file://). Conforma-se a
 * `MedScriptData` em types.ts. Todos os registros abaixo são de referência
 * pública ou sintéticos — sem PHI real.
 */
window.MEDSCRIPT_DATA = {
  schemaVersion: 1,
  lastUpdated: "2026-07-14T06:00:00-03:00",
  dailyCounts: {
    "2026-07-14": 5,
    "2026-07-13": 3,
    "2026-07-12": 2
  },
  entries: [
    {
      id: "med-paracetamol-ped-2026-07-14",
      type: "medication",
      title: "Paracetamol pediátrico — solução oral",
      summary: "Analgésico/antitérmico de primeira linha em pediatria, com dose ajustada por peso.",
      author: { name: "Anvisa / bulário eletrônico", credentials: "Órgão regulador", institution: "Anvisa" },
      source: { name: "Anvisa", url: "https://consultas.anvisa.gov.br/", tier: "gold", license: "public-domain" },
      dateAdded: "2026-07-14",
      datePublished: "2025-09-10",
      tags: ["pediatria", "analgésico", "antitérmico", "dose por peso"],
      lang: "pt",
      verified: true,
      genericName: "Paracetamol (acetaminofeno)",
      brandNames: ["Tylenol", "Dôrico"],
      drugClass: "Analgésico / antipirético",
      indications: ["Febre", "Dor leve a moderada"],
      controlStatus: "isento de prescrição",
      administration: "Via oral, 10–15 mg/kg/dose a cada 6h, máximo 4 doses/dia. Não exceder 75 mg/kg/dia. Solução oral gotas 200 mg/mL.",
      commonDoses: ["10–15 mg/kg/dose", "6/6h", "máx. 4x/dia"],
      contraindications: ["Insuficiência hepática grave", "Hipersensibilidade ao paracetamol"],
      adverseEffects: ["Hepatotoxicidade em superdose", "Reações cutâneas (raras)"],
      interactions: ["Álcool (hepatotoxicidade)", "Varfarina (potencializa em uso crônico)"],
      pregnancyCategory: "Uso permitido conforme avaliação médica",
      physicalId: "Solução oral em gotas, incolor a levemente amarelada; 200 mg/mL (1 gota ≈ 10 mg).",
      dosing: { mgPerKg: 15, maxDoseMg: 750, concentrationMgPerMl: 200, timesPerDay: 4, note: "15 mg/kg/dose, teto 750 mg/dose; volume calculado para solução 200 mg/mL." }
    },
    {
      id: "med-empagliflozina-2026-07-14",
      type: "medication",
      title: "Empagliflozina — inibidor de SGLT2",
      summary: "Antidiabético oral com benefício cardiovascular e renal comprovado em DM2 e insuficiência cardíaca.",
      author: { name: "Anvisa / bulário eletrônico", credentials: "Órgão regulador", institution: "Anvisa" },
      source: { name: "Anvisa", url: "https://consultas.anvisa.gov.br/", tier: "gold", license: "public-domain" },
      dateAdded: "2026-07-14",
      datePublished: "2025-11-02",
      tags: ["endocrinologia", "cardiologia", "DM2", "SGLT2"],
      lang: "pt",
      verified: true,
      genericName: "Empagliflozina",
      brandNames: ["Jardiance"],
      drugClass: "Inibidor de SGLT2",
      indications: ["Diabetes mellitus tipo 2", "Insuficiência cardíaca", "Doença renal crônica"],
      controlStatus: "sob prescrição",
      administration: "Via oral, 1x/dia pela manhã, com ou sem alimentos. Iniciar com 10 mg; titular para 25 mg conforme controle glicêmico e tolerância.",
      commonDoses: ["10 mg VO 1x/dia", "25 mg VO 1x/dia"],
      contraindications: ["TFG < 20 mL/min", "Cetoacidose diabética", "Hipersensibilidade ao fármaco"],
      adverseEffects: ["Infecção genital micótica", "Infecção urinária", "Depleção de volume/hipotensão", "Cetoacidose euglicêmica (rara)"],
      interactions: ["Diuréticos (risco de depleção volêmica)", "Insulina/sulfonilureias (risco de hipoglicemia)"],
      pregnancyCategory: "Não recomendado no 2º/3º trimestres",
      physicalId: "Comprimido revestido; 10 mg (amarelo-pálido, redondo) e 25 mg (amarelo-pálido, oval), gravado 'S10'/'S25'.",
      dosing: { mgPerKg: 0, maxDoseMg: 25, timesPerDay: 1, note: "Dose fixa (não é por peso em adultos): 10–25 mg/dia. Calculadora usa mg/kg apenas quando aplicável." }
    },
    {
      id: "presc-has-estagio1-2026-07-14",
      type: "prescription",
      title: "Modelo — Hipertensão arterial estágio 1",
      summary: "Prescrição de referência para HAS estágio 1 sem comorbidades, baseada na diretriz SBC 2020.",
      author: { name: "Dra. Referência Cardiologia", credentials: "MD", specialty: "Cardiologia", institution: "SBC (diretriz)" },
      source: { name: "Diretriz SBC 2020", tier: "verified", license: "fair-use-reference" },
      dateAdded: "2026-07-14",
      tags: ["cardiologia", "hipertensão", "modelo"],
      lang: "pt",
      verified: true,
      phiStatus: "synthetic",
      condition: "Hipertensão arterial estágio 1",
      presentation: "Paciente adulto, ~50 anos, assintomático, com PA de consultório 148/94 mmHg confirmada em 3 medidas e MAPA compatível. Sem lesão de órgão-alvo, sem diabetes. Risco cardiovascular baixo a moderado.",
      items: [
        { drug: "Losartana", dose: "50 mg", route: "VO", frequency: "1x/dia", duration: "uso contínuo" },
        { drug: "Hidroclorotiazida", dose: "25 mg", route: "VO", frequency: "1x/dia", duration: "uso contínuo" }
      ],
      rationale: "Monoterapia com BRA + diurético tiazídico em baixa dose conforme diretriz SBC para estágio 1 com meta < 140/90 mmHg. Associar MEV (dieta hipossódica, atividade física).",
      notes: "Reavaliar PA e função renal/eletrólitos em 4 semanas. Exemplo sintético — não é paciente real."
    },
    {
      id: "doc-diretriz-sepse-2026-07-14",
      type: "document",
      title: "Surviving Sepsis Campaign — atualização 2025",
      summary: "Diretriz internacional de manejo da sepse e choque séptico com pacote de primeira hora.",
      author: { name: "Society of Critical Care Medicine", credentials: "SCCM/ESICM", specialty: "Terapia Intensiva" },
      source: { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/", tier: "gold", license: "fair-use-reference" },
      dateAdded: "2026-07-14",
      datePublished: "2025-03-18",
      tags: ["UTI", "sepse", "emergência", "diretriz"],
      lang: "en",
      verified: true,
      format: "pdf",
      pages: 42
    },
    {
      id: "info-antibioticoterapia-2026-07-14",
      type: "information",
      title: "Princípios de antibioticoterapia empírica",
      summary: "Resumo de escolha de antimicrobiano empírico por sítio de infecção e perfil de resistência local.",
      author: { name: "Dr. Referência Infectologia", credentials: "MD, PhD", specialty: "Infectologia" },
      source: { name: "UpToDate (resumo)", tier: "verified", license: "fair-use-reference" },
      dateAdded: "2026-07-14",
      tags: ["infectologia", "antibiótico", "resistência"],
      lang: "pt",
      verified: false,
      body: "## Antibioticoterapia empírica\n- Considerar sítio, gravidade e epidemiologia local.\n- Descalonar após cultura.\n- Reavaliar em 48–72h.",
      category: "revisão"
    },
    {
      id: "record-dor-toracica-2026-07-13",
      type: "record",
      title: "Prontuário de referência — dor torácica na emergência",
      summary: "Caso sintético de dor torácica para treinamento de raciocínio clínico e triagem de SCA.",
      author: { name: "Dr. Referência Emergência", credentials: "MD", specialty: "Medicina de Emergência" },
      source: { name: "Base educacional sintética", tier: "community", license: "public-domain" },
      dateAdded: "2026-07-13",
      tags: ["emergência", "cardiologia", "caso", "educacional"],
      lang: "pt",
      verified: true,
      phiStatus: "synthetic",
      ageBand: "55-60",
      sex: "M",
      identification: "Iniciais fictícias J.S., masculino, 57 anos, procedente de zona urbana. Caso sintético para treinamento — não é paciente real.",
      anamnese: "Queixa principal: dor torácica há 2h. HDA: dor retroesternal opressiva, iniciada em repouso, irradiando para MSE, associada a sudorese e náusea, sem melhora com repouso. Antecedentes: HAS, tabagista 20 maços-ano, dislipidemia. Exame físico: PA 150/95, FC 98 bpm, ausculta cardíaca sem sopros, pulmões limpos.",
      diagnostico: "Hipótese: Síndrome coronariana aguda (angina instável / IAM sem supra a esclarecer). Diferenciais: dissecção de aorta, TEP, pericardite.",
      evolucao: "0h: ECG com infra de ST em V4-V6; AAS 300 mg VO, monitorização, O2 se SatO2<94%. 1h: 1ª troponina elevada → conduta como IAMSSST, iniciado protocolo, contactada hemodinâmica. 3h: estável, dor controlada, encaminhado à estratégia invasiva precoce. Caso sintético — não é paciente real."
    },
    {
      id: "med-tirzepatida-2026-07-13",
      type: "medication",
      title: "Tirzepatida — agonista duplo GIP/GLP-1",
      summary: "Incretinomimético para DM2 e obesidade com forte redução de HbA1c e peso.",
      author: { name: "FDA label", credentials: "Órgão regulador", institution: "FDA" },
      source: { name: "FDA", url: "https://www.accessdata.fda.gov/", tier: "gold", license: "public-domain" },
      dateAdded: "2026-07-13",
      datePublished: "2025-06-01",
      tags: ["endocrinologia", "obesidade", "DM2", "GLP-1"],
      lang: "en",
      verified: true,
      genericName: "Tirzepatida",
      brandNames: ["Mounjaro", "Zepbound"],
      drugClass: "Agonista de receptor GIP/GLP-1",
      indications: ["Diabetes mellitus tipo 2", "Obesidade"],
      controlStatus: "sob prescrição",
      administration: "Subcutânea, 1x/semana, mesmo dia da semana, com ou sem alimentos. Iniciar 2,5 mg/semana por 4 semanas; escalonar 2,5 mg a cada ≥4 semanas conforme resposta e tolerância.",
      commonDoses: ["2,5 mg SC 1x/semana (início)", "5–15 mg SC 1x/semana"],
      contraindications: ["Carcinoma medular de tireoide (pessoal/familiar)", "NEM 2", "Hipersensibilidade"],
      adverseEffects: ["Náusea", "Diarreia", "Vômito", "Constipação", "Risco de pancreatite (raro)"],
      interactions: ["Retarda esvaziamento gástrico (absorção de orais)", "Insulina/sulfonilureias (hipoglicemia)"],
      pregnancyCategory: "Evitar na gestação",
      physicalId: "Caneta/solução injetável SC; apresentações de 2,5 a 15 mg em canetas de dose única.",
      dosing: { mgPerKg: 0, maxDoseMg: 15, timesPerDay: 0, note: "Dose fixa semanal, não por peso. Escalonamento conforme tolerância." }
    },
    {
      id: "info-anticoagulacao-fa-2026-07-13",
      type: "information",
      title: "Anticoagulação na fibrilação atrial (CHA2DS2-VASc)",
      summary: "Estratificação de risco tromboembólico e escolha de anticoagulante oral na FA não valvar.",
      author: { name: "Dr. Referência Cardiologia", credentials: "MD", specialty: "Cardiologia" },
      source: { name: "Diretriz ESC (resumo)", tier: "verified", license: "fair-use-reference" },
      dateAdded: "2026-07-13",
      tags: ["cardiologia", "arritmia", "anticoagulação"],
      lang: "pt",
      verified: true,
      body: "## FA não valvar\n- CHA2DS2-VASc ≥ 2 (homens) / ≥ 3 (mulheres): anticoagular.\n- Preferir DOAC a varfarina quando elegível.",
      category: "diretriz"
    },
    {
      id: "doc-pals-2026-07-12",
      type: "document",
      title: "PALS — suporte avançado de vida pediátrico",
      summary: "Material de referência de reanimação pediátrica com algoritmos de PCR e bradicardia.",
      author: { name: "American Heart Association", credentials: "AHA", specialty: "Pediatria" },
      source: { name: "AHA", url: "https://cpr.heart.org/", tier: "gold", license: "fair-use-reference" },
      dateAdded: "2026-07-12",
      datePublished: "2025-01-10",
      tags: ["pediatria", "emergência", "reanimação"],
      lang: "en",
      verified: true,
      format: "pdf",
      pages: 30
    },
    {
      id: "presc-pneumonia-comunitaria-2026-07-12",
      type: "prescription",
      title: "Modelo — pneumonia adquirida na comunidade (ambulatorial)",
      summary: "Prescrição de referência para PAC de baixo risco em adulto hígido (CURB-65 baixo).",
      author: { name: "Dr. Referência Pneumologia", credentials: "MD", specialty: "Pneumologia" },
      source: { name: "Diretriz SBPT (resumo)", tier: "verified", license: "fair-use-reference" },
      dateAdded: "2026-07-12",
      tags: ["pneumologia", "infectologia", "modelo"],
      lang: "pt",
      verified: false,
      phiStatus: "synthetic",
      condition: "Pneumonia adquirida na comunidade (ambulatorial)",
      presentation: "Adulto ~35 anos, previamente hígido, com tosse produtiva, febre 38,5 °C há 3 dias, dor pleurítica leve. SatO2 97% em ar ambiente, FR 18, sem confusão. CURB-65 = 0. Radiografia com consolidação em base direita.",
      items: [
        { drug: "Amoxicilina", dose: "875 mg", route: "VO", frequency: "12/12h", duration: "7 dias" }
      ],
      rationale: "PAC de baixo risco, tratamento ambulatorial com betalactâmico conforme diretriz SBPT. Orientar sinais de alarme e retorno.",
      notes: "Alternativa em alergia: azitromicina 500 mg 1x/dia por 3 dias. Exemplo sintético — não é paciente real."
    }
  ]
};
